
nodeDrainerEnabled: true
containerdProxyEnabled: false
containerdProxy: ""
customCertsEnabled: false
customCerts: ""
customKubeletFlagsEnabled: false
customKubeletFlags: "--image-gc-low-threshold=90 --image-gc-high-threshold=95"

residentImage: "cr.yandex/yc/mk8s-openssl:stable"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

resources: {}

nodeSelector: {}
#  yandex.cloud/preemptible: "true"

#tolerationName: node-sitter

tolerations: []

affinity: {}
